version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-dev
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ../seed.sql:/docker-entrypoint-initdb.d/1_seed.sql:ro
    environment:
      CLICKHOUSE_USER: devuser
      CLICKHOUSE_PASSWORD: devpassword
    networks:
      - app-net


networks:
  app-net:
    driver: bridge
